// Code generated by sqlc. DO NOT EDIT.
// source: db.go

package sqlcdb

import "database/sql"

type DBTX interface {
	ExecContext(ctx interface{}, query string, args ...interface{}) (sql.Result, error)
	PrepareContext(ctx interface{}, query string) (*sql.Stmt, error)
	QueryContext(ctx interface{}, query string, args ...interface{}) (*sql.Rows, error)
	QueryRowContext(ctx interface{}, query string, args ...interface{}) *sql.Row
}
