// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AppState struct {
	Key       string          `json:"key"`
	ValueJson json.RawMessage `json:"value_json"`
	UpdatedAt time.Time       `json:"updated_at"`
}

type Task struct {
	ID                       string          `json:"id"`
	RepoFullName             string          `json:"repo_full_name"`
	IssueNumber              int64           `json:"issue_number"`
	IssueTitle               string          `json:"issue_title"`
	TaskType                 string          `json:"task_type"`
	Status                   string          `json:"status"`
	PromptTemplate           string          `json:"prompt_template"`
	WorktreePath             string          `json:"worktree_path"`
	PrUrl                    string          `json:"pr_url"`
	PrNumber                 int64           `json:"pr_number"`
	StartedAt                sql.NullTime    `json:"started_at"`
	FinishedAt               sql.NullTime    `json:"finished_at"`
	EstimatedInputTokens     int64           `json:"estimated_input_tokens"`
	EstimatedOutputTokens    int64           `json:"estimated_output_tokens"`
	ExitCode                 *int            `json:"exit_code"`
	StderrTail               string          `json:"stderr_tail"`
	CreatedAt                time.Time       `json:"created_at"`
	UpdatedAt                time.Time       `json:"updated_at"`
	Source                   string          `json:"source"`
	MaintenanceName          string          `json:"maintenance_name"`
	CostUsd                  string          `json:"cost_usd"`
	TotalInputTokens         int64           `json:"total_input_tokens"`
	TotalOutputTokens        int64           `json:"total_output_tokens"`
	CacheCreationInputTokens int64           `json:"cache_creation_input_tokens"`
	CacheReadInputTokens     int64           `json:"cache_read_input_tokens"`
	ModelUsageJson           json.RawMessage `json:"model_usage_json"`
	WorkerID                 sql.NullString  `json:"worker_id"`
	ClaimedAt                sql.NullTime    `json:"claimed_at"`
}

type TaskEvent struct {
	ID          string          `json:"id"`
	TaskID      string          `json:"task_id"`
	Kind        string          `json:"kind"`
	PayloadJson json.RawMessage `json:"payload_json"`
	CreatedAt   time.Time       `json:"created_at"`
}
