// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	// Caller resolves the day boundary in the configured tz and passes
	// [day_start, day_end) as a half-open range (e.g. 00:00:00.000 of day N
	// and day N+1). Range comparison lets MySQL use the timestamp index.
	SumDailyCost(ctx context.Context, arg SumDailyCostParams) (float64, error)
	SumUsageByDay(ctx context.Context, arg SumUsageByDayParams) ([]SumUsageByDayRow, error)
	SumUsageByModel(ctx context.Context, arg SumUsageByModelParams) ([]SumUsageByModelRow, error)
	SumUsageByMonth(ctx context.Context, arg SumUsageByMonthParams) ([]SumUsageByMonthRow, error)
	// ISO 8601 week (year-week, Monday start, week 1 contains Jan 4).
	SumUsageByWeek(ctx context.Context, arg SumUsageByWeekParams) ([]SumUsageByWeekRow, error)
	// Caller resolves the ISO 8601 week boundary in the configured tz and passes
	// [week_start, week_end) as a half-open range (Monday 00:00 of week N and N+1).
	SumWeeklyCost(ctx context.Context, arg SumWeeklyCostParams) (float64, error)
}

var _ Querier = (*Queries)(nil)
