// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	// Atomically pick one queued task and flip it to running. Skips:
	//   * Rows another transaction already locked (FOR UPDATE SKIP LOCKED) —
	//     this is what makes parallel workers race-free without an in-process mutex.
	//   * Rows whose repo already has a task in 'running' (NOT EXISTS subquery) —
	//     this serializes per-repo work even across workers, satisfying the
	//     parallel-tasks PRD's "same-repo never concurrent" rule at the SQL
	//     layer rather than relying on application-side mutexes.
	// The derived-table wrapping is required because MySQL refuses self-reference
	// in the same UPDATE/SELECT (Error 1093).
	ClaimNextTask(ctx context.Context, workerID sql.NullString) (int64, error)
	// Looks up the existing ci-fix child task for a given (parent, head_sha)
	// pair. Returns ErrNoRows when no duplicate exists, which the caller treats
	// as "free to enqueue".
	FindFixChildTaskID(ctx context.Context, arg FindFixChildTaskIDParams) (string, error)
	// Returns the most recently claimed task for a worker. Used right after
	// ClaimNextTask reports rowsAffected=1 to load the row.
	GetClaimedTaskID(ctx context.Context, workerID sql.NullString) (string, error)
	// Returns IDs of tasks the CI watcher should poll. Used by the watcher tick
	// so it can refresh state by calling repo.GetByID, keeping the loaded *Task
	// mapping in one place (the GORM repository).
	ListWatchingTaskIDs(ctx context.Context) ([]string, error)
	// Periodic safety net: marks tasks orphaned when their worker died without
	// clearing the claim. The cutoff is `now - lease_timeout`; rows still being
	// actively processed have a fresher claimed_at and survive.
	ReclaimStaleTasks(ctx context.Context, cutoff sql.NullTime) (int64, error)
	// Caller resolves the day boundary in the configured tz and passes
	// [day_start, day_end) as a half-open range (e.g. 00:00:00.000 of day N
	// and day N+1). Range comparison lets MySQL use the timestamp index.
	SumDailyCost(ctx context.Context, arg SumDailyCostParams) (float64, error)
	SumUsageByDay(ctx context.Context, arg SumUsageByDayParams) ([]SumUsageByDayRow, error)
	SumUsageByModel(ctx context.Context, arg SumUsageByModelParams) ([]SumUsageByModelRow, error)
	SumUsageByMonth(ctx context.Context, arg SumUsageByMonthParams) ([]SumUsageByMonthRow, error)
	// ISO 8601 week (year-week, Monday start, week 1 contains Jan 4).
	SumUsageByWeek(ctx context.Context, arg SumUsageByWeekParams) ([]SumUsageByWeekRow, error)
	// Caller resolves the ISO 8601 week boundary in the configured tz and passes
	// [week_start, week_end) as a half-open range (Monday 00:00 of week N and N+1).
	SumWeeklyCost(ctx context.Context, arg SumWeeklyCostParams) (float64, error)
	// Targeted update used by the CI watcher to advance ci_status / head_sha /
	// ci_last_polled_at without touching the rest of the row.
	UpdateTaskCIStatus(ctx context.Context, arg UpdateTaskCIStatusParams) error
}

var _ Querier = (*Queries)(nil)
