// Code generated by sqlc. DO NOT EDIT.
// source: queries.go

package sqlcdb

import (
	"context"
	"database/sql"
)

const listTasks = `-- name: ListTasks :many
SELECT id, repo_full_name, issue_number, issue_title, task_type, status,
       prompt_template, worktree_path, pr_url, pr_number,
       started_at, finished_at,
       estimated_input_tokens, estimated_output_tokens,
       exit_code, stderr_tail, created_at, updated_at
FROM tasks
WHERE (? IS NULL OR status = ?)
  AND (? IS NULL OR id < ?)
ORDER BY created_at DESC
LIMIT ?`

const countTasksByStatus = `-- name: CountTasksByStatus :many
SELECT status, COUNT(*) as count
FROM tasks
GROUP BY status`

const listEventsByTask = `-- name: ListEventsByTask :many
SELECT id, task_id, kind, payload_json, created_at
FROM task_events
WHERE task_id = ?
ORDER BY created_at DESC
LIMIT ?`

// Queries implements Querier using a raw *sql.DB.
type Queries struct {
	db *sql.DB
}

// New creates a new Queries instance.
func New(db *sql.DB) *Queries {
	return &Queries{db: db}
}

// ListTasks executes the ListTasks query.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.Status, arg.Status,
		arg.Cursor, arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListTasksRow
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.RepoFullName,
			&i.IssueNumber,
			&i.IssueTitle,
			&i.TaskType,
			&i.Status,
			&i.PromptTemplate,
			&i.WorktreePath,
			&i.PrURL,
			&i.PrNumber,
			&i.StartedAt,
			&i.FinishedAt,
			&i.EstimatedInputTokens,
			&i.EstimatedOutputTokens,
			&i.ExitCode,
			&i.StderrTail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// CountTasksByStatus executes the CountTasksByStatus query.
func (q *Queries) CountTasksByStatus(ctx context.Context) ([]CountTasksByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countTasksByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []CountTasksByStatusRow
	for rows.Next() {
		var i CountTasksByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// ListEventsByTask executes the ListEventsByTask query.
func (q *Queries) ListEventsByTask(ctx context.Context, arg ListEventsByTaskParams) ([]ListEventsByTaskRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTask, arg.TaskID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListEventsByTaskRow
	for rows.Next() {
		var i ListEventsByTaskRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Kind,
			&i.PayloadJSON,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
