// Code generated by sqlc. DO NOT EDIT.
// source: querier.go

package sqlcdb

import (
	"context"
	"database/sql"
	"time"
)

// ListTasksParams holds arguments for ListTasks.
type ListTasksParams struct {
	Status *string `json:"status"`
	Cursor *string `json:"cursor"`
	Limit  int64   `json:"limit"`
}

// ListTasksRow is a single row returned by ListTasks.
type ListTasksRow struct {
	ID                    string        `json:"id"`
	RepoFullName          string        `json:"repo_full_name"`
	IssueNumber           int64         `json:"issue_number"`
	IssueTitle            string        `json:"issue_title"`
	TaskType              string        `json:"task_type"`
	Status                string        `json:"status"`
	PromptTemplate        string        `json:"prompt_template"`
	WorktreePath          string        `json:"worktree_path"`
	PrURL                 string        `json:"pr_url"`
	PrNumber              int64         `json:"pr_number"`
	StartedAt             sql.NullTime  `json:"started_at"`
	FinishedAt            sql.NullTime  `json:"finished_at"`
	EstimatedInputTokens  int64         `json:"estimated_input_tokens"`
	EstimatedOutputTokens int64         `json:"estimated_output_tokens"`
	ExitCode              sql.NullInt64 `json:"exit_code"`
	StderrTail            string        `json:"stderr_tail"`
	CreatedAt             time.Time     `json:"created_at"`
	UpdatedAt             time.Time     `json:"updated_at"`
}

// CountTasksByStatusRow holds a status and its count.
type CountTasksByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

// ListEventsByTaskParams holds arguments for ListEventsByTask.
type ListEventsByTaskParams struct {
	TaskID string `json:"task_id"`
	Limit  int64  `json:"limit"`
}

// ListEventsByTaskRow is a single row returned by ListEventsByTask.
type ListEventsByTaskRow struct {
	ID          string    `json:"id"`
	TaskID      string    `json:"task_id"`
	Kind        string    `json:"kind"`
	PayloadJSON string    `json:"payload_json"`
	CreatedAt   time.Time `json:"created_at"`
}

// Querier is the sqlc-generated query interface.
type Querier interface {
	ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error)
	CountTasksByStatus(ctx context.Context) ([]CountTasksByStatusRow, error)
	ListEventsByTask(ctx context.Context, arg ListEventsByTaskParams) ([]ListEventsByTaskRow, error)
	SumUsageByDay(ctx context.Context, arg SumUsageByDayParams) ([]SumUsageByDayRow, error)
	SumUsageByWeek(ctx context.Context, arg SumUsageByWeekParams) ([]SumUsageByDayRow, error)
	SumUsageByMonth(ctx context.Context, arg SumUsageByMonthParams) ([]SumUsageByDayRow, error)
	SumUsageByModel(ctx context.Context, arg SumUsageByModelParams) ([]SumUsageByModelRow, error)
	SumDailyCost(ctx context.Context, dayKey string) (float64, error)
	SumWeeklyCost(ctx context.Context, weekKey string) (float64, error)
}
