// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package sqlcdb

import (
	"context"
	"database/sql"
	"encoding/json"
)

const sumDailyCost = `-- name: SumDailyCost :one
SELECT CAST(COALESCE(SUM(cost_usd), 0) AS DOUBLE) AS total_cost
FROM tasks
WHERE status = 'done'
  AND COALESCE(finished_at, created_at) >= ?
  AND COALESCE(finished_at, created_at) <  ?
`

type SumDailyCostParams struct {
	DayStart sql.NullTime `json:"day_start"`
	DayEnd   sql.NullTime `json:"day_end"`
}

// Caller resolves the day boundary in the configured tz and passes
// [day_start, day_end) as a half-open range (e.g. 00:00:00.000 of day N
// and day N+1). Range comparison lets MySQL use the timestamp index.
func (q *Queries) SumDailyCost(ctx context.Context, arg SumDailyCostParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumDailyCost, arg.DayStart, arg.DayEnd)
	var total_cost float64
	err := row.Scan(&total_cost)
	return total_cost, err
}

const sumUsageByDay = `-- name: SumUsageByDay :many
SELECT
    DATE_FORMAT(COALESCE(finished_at, created_at), '%Y-%m-%d')                                                AS bucket,
    CAST(SUM(CASE WHEN status = 'done' THEN 1 ELSE 0 END) AS SIGNED)                                          AS task_count,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cost_usd ELSE 0 END), 0) AS DOUBLE)                      AS cost_usd,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN total_input_tokens ELSE 0 END), 0) AS SIGNED)            AS input_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN total_output_tokens ELSE 0 END), 0) AS SIGNED)           AS output_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cache_read_input_tokens ELSE 0 END), 0) AS SIGNED)       AS cache_read_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cache_creation_input_tokens ELSE 0 END), 0) AS SIGNED)   AS cache_creation_tokens,
    CAST(COALESCE(SUM(CASE WHEN status IN ('failed', 'cancelled') THEN cost_usd ELSE 0 END), 0) AS DOUBLE)    AS failed_cost_usd
FROM tasks
WHERE COALESCE(finished_at, created_at) >= ?
  AND COALESCE(finished_at, created_at) <  ?
GROUP BY bucket
ORDER BY bucket
`

type SumUsageByDayParams struct {
	FromTs sql.NullTime `json:"from_ts"`
	ToTs   sql.NullTime `json:"to_ts"`
}

type SumUsageByDayRow struct {
	Bucket              string  `json:"bucket"`
	TaskCount           int64   `json:"task_count"`
	CostUsd             float64 `json:"cost_usd"`
	InputTokens         int64   `json:"input_tokens"`
	OutputTokens        int64   `json:"output_tokens"`
	CacheReadTokens     int64   `json:"cache_read_tokens"`
	CacheCreationTokens int64   `json:"cache_creation_tokens"`
	FailedCostUsd       float64 `json:"failed_cost_usd"`
}

func (q *Queries) SumUsageByDay(ctx context.Context, arg SumUsageByDayParams) ([]SumUsageByDayRow, error) {
	rows, err := q.db.QueryContext(ctx, sumUsageByDay, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUsageByDayRow{}
	for rows.Next() {
		var i SumUsageByDayRow
		if err := rows.Scan(
			&i.Bucket,
			&i.TaskCount,
			&i.CostUsd,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
			&i.FailedCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUsageByModel = `-- name: SumUsageByModel :many
SELECT
    CAST(cost_usd AS DOUBLE)                                                                                  AS cost_usd,
    model_usage_json,
    total_input_tokens,
    total_output_tokens,
    cache_read_input_tokens,
    cache_creation_input_tokens
FROM tasks
WHERE status = 'done'
  AND COALESCE(finished_at, created_at) >= ?
  AND COALESCE(finished_at, created_at) <  ?
`

type SumUsageByModelParams struct {
	FromTs sql.NullTime `json:"from_ts"`
	ToTs   sql.NullTime `json:"to_ts"`
}

type SumUsageByModelRow struct {
	CostUsd                  float64         `json:"cost_usd"`
	ModelUsageJson           json.RawMessage `json:"model_usage_json"`
	TotalInputTokens         int64           `json:"total_input_tokens"`
	TotalOutputTokens        int64           `json:"total_output_tokens"`
	CacheReadInputTokens     int64           `json:"cache_read_input_tokens"`
	CacheCreationInputTokens int64           `json:"cache_creation_input_tokens"`
}

func (q *Queries) SumUsageByModel(ctx context.Context, arg SumUsageByModelParams) ([]SumUsageByModelRow, error) {
	rows, err := q.db.QueryContext(ctx, sumUsageByModel, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUsageByModelRow{}
	for rows.Next() {
		var i SumUsageByModelRow
		if err := rows.Scan(
			&i.CostUsd,
			&i.ModelUsageJson,
			&i.TotalInputTokens,
			&i.TotalOutputTokens,
			&i.CacheReadInputTokens,
			&i.CacheCreationInputTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUsageByMonth = `-- name: SumUsageByMonth :many
SELECT
    DATE_FORMAT(COALESCE(finished_at, created_at), '%Y-%m')                                                   AS bucket,
    CAST(SUM(CASE WHEN status = 'done' THEN 1 ELSE 0 END) AS SIGNED)                                          AS task_count,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cost_usd ELSE 0 END), 0) AS DOUBLE)                      AS cost_usd,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN total_input_tokens ELSE 0 END), 0) AS SIGNED)            AS input_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN total_output_tokens ELSE 0 END), 0) AS SIGNED)           AS output_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cache_read_input_tokens ELSE 0 END), 0) AS SIGNED)       AS cache_read_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cache_creation_input_tokens ELSE 0 END), 0) AS SIGNED)   AS cache_creation_tokens,
    CAST(COALESCE(SUM(CASE WHEN status IN ('failed', 'cancelled') THEN cost_usd ELSE 0 END), 0) AS DOUBLE)    AS failed_cost_usd
FROM tasks
WHERE COALESCE(finished_at, created_at) >= ?
  AND COALESCE(finished_at, created_at) <  ?
GROUP BY bucket
ORDER BY bucket
`

type SumUsageByMonthParams struct {
	FromTs sql.NullTime `json:"from_ts"`
	ToTs   sql.NullTime `json:"to_ts"`
}

type SumUsageByMonthRow struct {
	Bucket              string  `json:"bucket"`
	TaskCount           int64   `json:"task_count"`
	CostUsd             float64 `json:"cost_usd"`
	InputTokens         int64   `json:"input_tokens"`
	OutputTokens        int64   `json:"output_tokens"`
	CacheReadTokens     int64   `json:"cache_read_tokens"`
	CacheCreationTokens int64   `json:"cache_creation_tokens"`
	FailedCostUsd       float64 `json:"failed_cost_usd"`
}

func (q *Queries) SumUsageByMonth(ctx context.Context, arg SumUsageByMonthParams) ([]SumUsageByMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, sumUsageByMonth, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUsageByMonthRow{}
	for rows.Next() {
		var i SumUsageByMonthRow
		if err := rows.Scan(
			&i.Bucket,
			&i.TaskCount,
			&i.CostUsd,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
			&i.FailedCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUsageByWeek = `-- name: SumUsageByWeek :many
SELECT
    DATE_FORMAT(COALESCE(finished_at, created_at), '%x-W%v')                                                  AS bucket,
    CAST(SUM(CASE WHEN status = 'done' THEN 1 ELSE 0 END) AS SIGNED)                                          AS task_count,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cost_usd ELSE 0 END), 0) AS DOUBLE)                      AS cost_usd,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN total_input_tokens ELSE 0 END), 0) AS SIGNED)            AS input_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN total_output_tokens ELSE 0 END), 0) AS SIGNED)           AS output_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cache_read_input_tokens ELSE 0 END), 0) AS SIGNED)       AS cache_read_tokens,
    CAST(COALESCE(SUM(CASE WHEN status = 'done' THEN cache_creation_input_tokens ELSE 0 END), 0) AS SIGNED)   AS cache_creation_tokens,
    CAST(COALESCE(SUM(CASE WHEN status IN ('failed', 'cancelled') THEN cost_usd ELSE 0 END), 0) AS DOUBLE)    AS failed_cost_usd
FROM tasks
WHERE COALESCE(finished_at, created_at) >= ?
  AND COALESCE(finished_at, created_at) <  ?
GROUP BY bucket
ORDER BY bucket
`

type SumUsageByWeekParams struct {
	FromTs sql.NullTime `json:"from_ts"`
	ToTs   sql.NullTime `json:"to_ts"`
}

type SumUsageByWeekRow struct {
	Bucket              string  `json:"bucket"`
	TaskCount           int64   `json:"task_count"`
	CostUsd             float64 `json:"cost_usd"`
	InputTokens         int64   `json:"input_tokens"`
	OutputTokens        int64   `json:"output_tokens"`
	CacheReadTokens     int64   `json:"cache_read_tokens"`
	CacheCreationTokens int64   `json:"cache_creation_tokens"`
	FailedCostUsd       float64 `json:"failed_cost_usd"`
}

// ISO 8601 week (year-week, Monday start, week 1 contains Jan 4).
func (q *Queries) SumUsageByWeek(ctx context.Context, arg SumUsageByWeekParams) ([]SumUsageByWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, sumUsageByWeek, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUsageByWeekRow{}
	for rows.Next() {
		var i SumUsageByWeekRow
		if err := rows.Scan(
			&i.Bucket,
			&i.TaskCount,
			&i.CostUsd,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheCreationTokens,
			&i.FailedCostUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumWeeklyCost = `-- name: SumWeeklyCost :one
SELECT CAST(COALESCE(SUM(cost_usd), 0) AS DOUBLE) AS total_cost
FROM tasks
WHERE status = 'done'
  AND COALESCE(finished_at, created_at) >= ?
  AND COALESCE(finished_at, created_at) <  ?
`

type SumWeeklyCostParams struct {
	WeekStart sql.NullTime `json:"week_start"`
	WeekEnd   sql.NullTime `json:"week_end"`
}

// Caller resolves the ISO 8601 week boundary in the configured tz and passes
// [week_start, week_end) as a half-open range (Monday 00:00 of week N and N+1).
func (q *Queries) SumWeeklyCost(ctx context.Context, arg SumWeeklyCostParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, sumWeeklyCost, arg.WeekStart, arg.WeekEnd)
	var total_cost float64
	err := row.Scan(&total_cost)
	return total_cost, err
}
