// Code generated by mockery v2. DO NOT EDIT.
// Run: mockery --name=UsageRepository --dir=internal/domain --output=mocks

package mocks

import (
	"context"
	"time"

	"github.com/stretchr/testify/mock"

	"github.com/gs97ahn/claude-ops/internal/domain"
)

// UsageRepository is a mock for domain.UsageRepository.
type UsageRepository struct {
	mock.Mock
}

// SumByBucket mocks domain.UsageRepository.SumByBucket.
func (m *UsageRepository) SumByBucket(ctx context.Context, from, to time.Time, bucket domain.BucketKind) ([]domain.UsageBucketRow, error) {
	args := m.Called(ctx, from, to, bucket)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]domain.UsageBucketRow), args.Error(1)
}

// SumByModel mocks domain.UsageRepository.SumByModel.
func (m *UsageRepository) SumByModel(ctx context.Context, from, to time.Time) ([]domain.UsageModelRow, error) {
	args := m.Called(ctx, from, to)
	if args.Get(0) == nil {
		return nil, args.Error(1)
	}
	return args.Get(0).([]domain.UsageModelRow), args.Error(1)
}

// SumDailyCost mocks domain.UsageRepository.SumDailyCost.
func (m *UsageRepository) SumDailyCost(ctx context.Context, dayKey string) (float64, error) {
	args := m.Called(ctx, dayKey)
	return args.Get(0).(float64), args.Error(1)
}

// SumWeeklyCost mocks domain.UsageRepository.SumWeeklyCost.
func (m *UsageRepository) SumWeeklyCost(ctx context.Context, weekKey string) (float64, error) {
	args := m.Called(ctx, weekKey)
	return args.Get(0).(float64), args.Error(1)
}
